version: "3"

networks: 
  classicpress_network:
    driver: bridge

secrets:
  CP_DB_PASSWORD:
    file: ./secrets/CP_DB_PASSWORD.secret
  DB_ROOT_PASSWORD:
    file: ./secrets/DB_ROOT_PASSWORD.secret

services:
  classicpress:
    build: classicpress
    volumes:
    - ./data/classicpress:/data
    networks:
    - classicpress_network
    ports:
    - 8000:80
    depends_on:
    - mariadb
    environment:
    - "APACHE_RUN_USER_ID=${UID}"
    - "APACHE_RUN_GROUP_ID=${GID}"
    - "CP_DB_NAME=${CP_DB_NAME}"
    - "CP_DB_USER=${CP_DB_USER}"
    - "CP_DB_PASSWORD_FILE=/run/secrets/CP_DB_PASSWORD"
    - "CP_DB_HOST=${CP_DB_HOST}"
    secrets:
    - CP_DB_PASSWORD
    restart: unless-stopped

  mariadb:
    image: mariadb:10.7.3
    container_name: "${CP_DB_HOST}"
    volumes:
    - ./data/mariadb:/var/lib/mysql
    networks:
    - classicpress_network
    environment:
    - "MARIADB_DATABASE=${CP_DB_NAME}"
    - "MARIADB_USER=${CP_DB_USER}"
    - "MARIADB_PASSWORD_FILE=/run/secrets/MARIADB_PASSWORD"
    - "MARIADB_ROOT_PASSWORD_FILE=/run/secrets/MARIADB_ROOT_PASSWORD"
    secrets:
    - source: CP_DB_PASSWORD
      target: MARIADB_PASSWORD
    - source: DB_ROOT_PASSWORD
      target: MARIADB_ROOT_PASSWORD
    restart: unless-stopped
