version: "3"

networks: 
  myblog_network:
    driver: bridge

volumes:
  myblog_data:
  mariadb_data:

secrets:
  MYBLOG_DB_PASSWORD:
    file: ./MYBLOG_DB_PASSWORD.secret
  MARIADB_ROOT_PASSWORD:
    file: ./MARIADB_ROOT_PASSWORD.secret

services:
  classicpress:
    image: marverix/classicpress:latest
    container_name: "${MYBLOG}"
    volumes:
    - myblog_data:/data
    networks:
    - myblog_network
    ports:
    - 8000:80
    depends_on:
    - mariadb
    environment:
    - "APACHE_RUN_USER_ID=${UID}"
    - "APACHE_RUN_GROUP_ID=${GID}"
    - "CP_DB_NAME=${MYBLOG}_db"
    - "CP_DB_USER=${MYBLOG}_user"
    - "CP_DB_PASSWORD_FILE=/run/secrets/MYBLOG_DB_PASSWORD"
    - "CP_DB_HOST=mariadb"
    secrets:
    - MYBLOG_DB_PASSWORD
    restart: unless-stopped

  mariadb:
    image: mariadb:10.7.3
    container_name: mariadb
    volumes:
    - mariadb_data:/var/lib/mysql/data
    networks:
    - myblog_network
    environment:
    - "MARIADB_DATABASE=${MYBLOG}_db"
    - "MARIADB_USER=${MYBLOG}_user"
    - "MARIADB_PASSWORD_FILE=/run/secrets/MYBLOG_DB_PASSWORD"
    - "MARIADB_ROOT_PASSWORD_FILE=/run/secrets/MARIADB_ROOT_PASSWORD"
    secrets:
    - MARIADB_ROOT_PASSWORD
    restart: unless-stopped
