networks: 
  classicpress_network:
    driver: bridge

secrets:
  CP_DB_PASSWORD:
    file: ./test/CP_DB_PASSWORD
  DB_ROOT_PASSWORD:
    file: ./test/DB_ROOT_PASSWORD

services:
  classicpress:
    build: classicpress
    volumes:
    - ./data/classicpress:/data
    networks:
    - classicpress_network
    ports:
    - 8000:80
    depends_on:
    - mariadb
    environment:
    - "CP_DB_NAME=${CP_DB_NAME}"
    - "CP_DB_USER=${CP_DB_USER}"
    - "CP_DB_PASSWORD_FILE=/run/secrets/CP_DB_PASSWORD"
    - "CP_DB_HOST=${CP_DB_HOST}"
    secrets:
    - CP_DB_PASSWORD
    restart: unless-stopped

  mariadb:
    image: mariadb:10.7.3
    container_name: mariadb
    volumes:
    - ./data/mariadb:/var/lib/mysql
    networks:
    - classicpress_network
    environment:
    - "MARIADB_DATABASE=${CP_DB_NAME}"
    - "MARIADB_USER=${CP_DB_USER}"
    - "MARIADB_PASSWORD_FILE=/run/secrets/MARIADB_PASSWORD"
    - "MARIADB_ROOT_PASSWORD_FILE=/run/secrets/MARIADB_ROOT_PASSWORD"
    secrets:
    - source: CP_DB_PASSWORD
      target: MARIADB_PASSWORD
    - source: DB_ROOT_PASSWORD
      target: MARIADB_ROOT_PASSWORD
    restart: unless-stopped
