name: CI

on:
  push:
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: marverix/classicpress

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get ClassicPress version
        id: version
        working-directory: classicpress
        run: |
          version=$(grep -oP 'ARG version=\K[0-9.]+(?=)' Dockerfile | xargs)
          echo "value=${version}" >> $GITHUB_OUTPUT

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
        name: Log into registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PTA }}

      - name: Set Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.version.outputs.value }}
            type=raw,value={{date 'YYYYMMDD-hhmmss' tz='Europe/Warsaw'}}
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=ClassicPress
            org.opencontainers.image.version=${{ steps.version.outputs.value }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.created={{date 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'}}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./classicpress
          push: false
          load: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Test
        working-directory: test
        run: |
          docker compose \
            --file run-tests.yaml \
            --progress quiet \
            up \
            --abort-on-container-exit k6 \
            --exit-code-from k6

      - if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
        name: Push
        uses: docker/build-push-action@v4
        with:
          context: ./classicpress
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
        name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
          short-description: ClassicPress Docker Image
